/**
 * Antigravity Dev - Auto-generated TypeScript Interfaces
 *
 * DO NOT EDIT THIS FILE MANUALLY!
 *
 * This file is automatically generated from Python Pydantic models.
 * To regenerate, run: python backend/scripts/sync_schema.py
 *
 * Source files:
 *   - libs/gravity_core/schema.py (Agent & Tool schemas)
 *   - backend/app/db/models.py (Database entities)
 *
 * Generated: 2025-12-07T17:37:00.234011
 */

// =============================================================================
// Agent & Tool Schemas (from libs/gravity_core/schema.py)
// =============================================================================

export interface AgentOutput {
  ui_title: string;
  ui_subtitle: string;
  technical_reasoning: string;
  tool_calls?: ToolCall[];
  confidence_score: number;
  agent_persona: AgentPersona;
  timestamp?: string;
}

export interface ToolCall {
  id?: string;
  tool_name: string;
  arguments?: Record<string, unknown>;
  result?: unknown;
  success?: boolean;
  error?: unknown;
  duration_ms?: unknown;
}

export interface TaskPlan {
  task_id?: string;
  summary: string;
  steps: TaskStep[];
  estimated_complexity: number;
  affected_files?: string[];
  risks?: string[];
}

export interface TaskStep {
  order: number;
  description: string;
  agent_persona: AgentPersona;
  estimated_tokens?: unknown;
  dependencies?: number[];
  files_affected?: string[];
}

export interface ChangeSet {
  file_path: string;
  action: string;
  diff: string;
  explanation: string;
  language?: unknown;
  line_count_before?: unknown;
  line_count_after?: unknown;
}

export interface ExecutionRun {
  command: string;
  working_directory: string;
  stdout?: string;
  stderr?: string;
  exit_code: number;
  duration_ms: number;
}

export interface DocUpdateLog {
  files_updated: string[];
  changes: ChangeSet[];
  summary: string;
}

export type TaskStatus = "pending" | "planning" | "plan_review" | "executing" | "testing" | "documenting" | "completed" | "failed" | "review_required";

export type AgentPersona = "planner" | "coder_be" | "coder_fe" | "coder_infra" | "qa" | "docs";

// =============================================================================
// Database Entities (from backend/app/db/models.py)
// =============================================================================

export interface Repository {
  id: string;
  name: string;
  path: string;
  description?: string | null;
  project_type?: string | null;
  framework?: string | null;
  created_at: string;
  updated_at: string;
}

export interface Task {
  id: string;
  repo_id: string;
  user_request: string;
  title?: string | null;
  status: TaskStatus;
  current_agent?: string | null;
  current_step: number;
  task_plan?: Record<string, unknown> | null;
  error_message?: string | null;
  retry_count: number;
  created_at: string;
  updated_at: string;
  completed_at?: string | null;
}

export interface AgentLog {
  id: string;
  task_id: string;
  agent_persona: string;
  step_number: number;
  ui_title: string;
  ui_subtitle: string;
  technical_reasoning: string;
  tool_calls?: Record<string, unknown>[] | null;
  confidence_score: number;
  requires_review: boolean;
  reviewed_at?: string | null;
  reviewed_by?: string | null;
  created_at: string;
  duration_ms?: number | null;
}

export interface ChangeSetDB {
  id: string;
  task_id: string;
  agent_log_id: string;
  file_path: string;
  action: string;
  diff: string;
  explanation: string;
  language?: string | null;
  lines_added: number;
  lines_removed: number;
  applied: boolean;
  reverted: boolean;
  created_at: string;
}
