"""Initial database schema

Revision ID: 5803305ba5cd
Revises:
Create Date: 2025-12-07 19:00:59.061281

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5803305ba5cd'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_type', sa.String(length=50), nullable=True),
    sa.Column('framework', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_table('repository_secrets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('key_name', sa.String(length=255), nullable=False, comment=(
        "Environment variable name (e.g., 'STRIPE_API_KEY')"
    )),
    sa.Column('encrypted_value', sa.Text(), nullable=False, comment=(
        'Fernet-encrypted secret value'
    )),
    sa.Column('description', sa.Text(), nullable=True, comment=(
        'Optional description of what this secret is used for'
    )),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('user_request', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum(
        'PENDING', 'PLANNING', 'PLAN_REVIEW', 'EXECUTING', 'TESTING',
        'DOCUMENTING', 'COMPLETED', 'FAILED', 'REVIEW_REQUIRED',
        name='taskstatus'
    ), nullable=False),
    sa.Column('current_agent', sa.String(length=50), nullable=True),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('task_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('agent_persona', sa.String(length=50), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('ui_title', sa.String(length=255), nullable=False),
    sa.Column('ui_subtitle', sa.Text(), nullable=False),
    sa.Column('technical_reasoning', sa.Text(), nullable=False),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('requires_review', sa.Boolean(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('changesets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('agent_log_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('diff', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('lines_added', sa.Integer(), nullable=False),
    sa.Column('lines_removed', sa.Integer(), nullable=False),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('reverted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_log_id'], ['agent_logs.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('changesets')
    op.drop_table('agent_logs')
    op.drop_table('tasks')
    op.drop_table('repository_secrets')
    op.drop_table('repositories')
    # ### end Alembic commands ###
